### ISSUE TITLE
Shooter isUpToSpeed isn't working for BMS

### ISSUE THREAD

**Issue by cpostbitbuckets** [BitBucketsFRC4183/FRC2022-Rapid-React#113] opened 2022-02-27 06:11 UTC
After testing, we realized the isUpToSpeed was only stopping the feeder motor, not the BMS, so the BMS was still feeding balls in even if the feeder was stopped.

We added code to check isUpToSpeed and shooter state in the Robot.java and spin/stop the BMS. Something is wrong though, the BMS only twitches and then immediately stops. The feeder works correctly though...

**Comment by cal-miller-harvard** [comment] 2022-02-27 06:47
I think that the problem is that you're both setting the state of the BMS in [teleopPeriodic](https://github.com/BitBucketsFRC4183/FRC2022-Rapid-React/blob/70116dcd6c88182797c151ff6cb60943186d02d6/RapidReact/src/main/java/frc/robot/Robot.java#L267) and using [the buttons](https://github.com/BitBucketsFRC4183/FRC2022-Rapid-React/blob/70116dcd6c88182797c151ff6cb60943186d02d6/RapidReact/src/main/java/frc/robot/Robot.java#L406). Those two might be fighting over the state of the system and making it misbehave.

As always, the **correct** solution is to avoid this sort of bug in the first place and write a fully specified finite state machine describing the system's desired behavior. But you might get away with removing the button manually controlling the BMS [here](https://github.com/BitBucketsFRC4183/FRC2022-Rapid-React/blob/70116dcd6c88182797c151ff6cb60943186d02d6/RapidReact/src/main/java/frc/robot/Robot.java#L406). You'll also want to fix the logic so that the BMS  (and feeder, I guess) doesn't run whenever the shooter is turned on and up to speed, but so it runs when those conditions are met AND the shoot button is pressed.

Let me know if those changes fix the problem!

**Comment by ojas-sanghi** [comment] 2022-02-27 21:39
fixed in #118

**Comment by ojas-sanghi** [comment] 2022-03-02 05:14
This should be closed

**Closed** 2022-03-19 05:16 UTC
